What is pandas?

Pandas is a fast , powerful, flexible and easy to use open source data analysis, and manipulation tool, built on top of the python programming language.

1. Pandas Series

In [10]:
# i. series from a list
import pandas as pd
import numpy as np
country=['Nepal','India','USA']
pd.Series(country)

0    Nepal
1    India
2      USA
dtype: object

In [11]:
#series with integer list
runs=[34,45,67,89]
pd.Series(runs)

0    34
1    45
2    67
3    89
dtype: int64

In [12]:
#custom index
marks=[67,78,89,87,99]
subjects=['English','Chemistry','Physics','Maths','Computer']
pd.Series(marks,index=subjects,name="Deep's marks")

English      67
Chemistry    78
Physics      89
Maths        87
Computer     99
Name: Deep's marks, dtype: int64

In [13]:
# ii. series from dictionary
marks={
    'physics':89,
    'maths':88
}
pd.Series(marks,name="Deep ko marks")

physics    89
maths      88
Name: Deep ko marks, dtype: int64

In [14]:
##iii. Series from excel(read_csv)

#dataframe
 
df=pd.read_csv('/workspaces/Pandas-Series/bollywood.csv',index_col='movie')
movies=df.squeeze()
movies


movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...       
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [15]:
df=pd.read_csv('/workspaces/Pandas-Series/kohli_ipl.csv', index_col='match_no' )
vk=df.squeeze()
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [16]:
subs=pd.read_csv('/workspaces/Pandas-Series/subs.csv')
subs

Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [8]:
movies['Mission Mangal']

'Akshay Kumar'

In [23]:
#series attributes
vk.size
vk.name
vk.count
vk.dtype
vk.is_unique
vk.index
vk.values

array([  1,  23,  13,  12,   1,   9,  34,   0,  21,   3,  10,  38,   3,
        11,  50,   2,  22,  19,  16,  15,  20,  38,  19,  24,   7,   2,
        16,  17,  24,  38,  34,  42,  13,  58,   3,  14,  37,   9,  23,
        12,  71,  35,  30,  56,  67,  27,  27,  39,  15,  11,  31,  70,
         8,  35,   8,   6,  57,  22,  16,   4,  16,  18,  45,   9,  36,
         9,   3,  73,  42,  24,  51,  35,  58,  65,   1,  11,   1,  32,
        25,  57,  93,  99,  17,  14,  56,  49,   0,  31,  21,   4,   0,
        35,   0,   4,  10,  27,  67,  38,  73,  13,  41,  18,  51,  62,
        35,   1,  34,  48,  32,  82,  19,  44,   1,  12,  12,  75,  79,
        33,  80, 100,  14,  52, 108,  20,   7, 109,  75, 113,  54,   0,
        54,  62,  28,  64,   0,  10,  55,  20,   6,   5,  58,  31,  21,
        57,  92,  30,  18,  68,  32,   8,  39,  70,  48,  12,   4,   6,
        46,   3,  23,  84,  41,  67,   8, 100,   9,  13,  23,  25,  16,
        18,   9,   7,  29,   1,  72,  43,  43,  90,  48,  14,  3

In [27]:
#Series Methods
#i. series.head()/series.tail()
vk.head()#displays first five datas
vk.tail()#displays last five datas

vk.head(3)#displays first 3 datas
vk.tail(2)#displays last 2 datas

match_no
214    25
215     7
Name: runs, dtype: int64

In [29]:
#ii. series.sample()
vk.sample()#randomly selects one of the data, 
movies.sample(5)#randomly selects 5 datas

movie
Aksar                        Emraan Hashmi
Devdas (2002 Hindi film)    Shah Rukh Khan
Gulaal (film)                Kay Kay Menon
Chargesheet (film)               Dev Anand
The Zoya Factor (film)        Sonam Kapoor
Name: lead, dtype: object

In [30]:
#ii. values_count()
movies.value_counts()#frequency counts on the basis of repetition of the values

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [36]:
#iii. sort_values
vk.sort_values(ascending=False)#sorting on the basis of value
#ascending=True for ascending order and False for descending order
#inplace=True for permanent change in the original series

match_no
128    113
126    109
123    108
164    100
120    100
      ... 
93       0
211      0
130      0
8        0
135      0
Name: runs, Length: 215, dtype: int64

In [37]:
#iv. sort_index
movies.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...        
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

Series Maths Methods

In [38]:
#i. count(counts number of data in the series)
print(vk.count)

<bound method Series.count of match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64>


In [44]:
#ii. mean/median/mode/std/var
print(subs.mean())
print(subs.median())
print(movies.mode())
print(vk.std())#standard deviation
print(vk.var())#varience

Subscribers gained    135.643836
dtype: float64
Subscribers gained    123.0
dtype: float64
0    Akshay Kumar
Name: lead, dtype: object
26.22980132830278
688.0024777222343


In [48]:
#iii. min/max
#use case : i want to know the maximum runs scored by virat kohli in IPL
print(vk.max())

print(vk.min())#minm runs scored by vk in ipl

113
0


In [49]:
#iv. describe
#describes overall data
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

In [51]:
movies.describe()

count             1500
unique             566
top       Akshay Kumar
freq                48
Name: lead, dtype: object

In [52]:
#v. sum/product 
#use case: to calculate overall subscriber gained in the last year
subs.sum()

Subscribers gained    49510
dtype: int64

Series with python functions


In [60]:
#i. len/type/dir/sorted/max/min
print(len(movies))#length of series
print(type(movies))#type of input data
print(dir(subs))#dir function gives all the methods used 
print(sorted(movies))#sorting on the basis of values
print(sorted(movies.index))#sorting on the basis of index
print(max(vk))
print(min(vk))

1500
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rd

In [68]:
#ii. type conversion
##we can convert python series to list or other data types of python
scores=list(vk.values)
print(scores)
movie=dict(movies)#gives dictionary of movies series
print(movie)

[1, 23, 13, 12, 1, 9, 34, 0, 21, 3, 10, 38, 3, 11, 50, 2, 22, 19, 16, 15, 20, 38, 19, 24, 7, 2, 16, 17, 24, 38, 34, 42, 13, 58, 3, 14, 37, 9, 23, 12, 71, 35, 30, 56, 67, 27, 27, 39, 15, 11, 31, 70, 8, 35, 8, 6, 57, 22, 16, 4, 16, 18, 45, 9, 36, 9, 3, 73, 42, 24, 51, 35, 58, 65, 1, 11, 1, 32, 25, 57, 93, 99, 17, 14, 56, 49, 0, 31, 21, 4, 0, 35, 0, 4, 10, 27, 67, 38, 73, 13, 41, 18, 51, 62, 35, 1, 34, 48, 32, 82, 19, 44, 1, 12, 12, 75, 79, 33, 80, 100, 14, 52, 108, 20, 7, 109, 75, 113, 54, 0, 54, 62, 28, 64, 0, 10, 55, 20, 6, 5, 58, 31, 21, 57, 92, 30, 18, 68, 32, 8, 39, 70, 48, 12, 4, 6, 46, 3, 23, 84, 41, 67, 8, 100, 9, 13, 23, 25, 16, 18, 9, 7, 29, 1, 72, 43, 43, 90, 48, 14, 33, 50, 8, 6, 33, 33, 5, 72, 8, 12, 35, 5, 25, 5, 4, 25, 51, 53, 39, 41, 12, 5, 48, 1, 12, 0, 0, 9, 58, 30, 0, 20, 73, 25, 7]
{'Uri: The Surgical Strike': 'Vicky Kaushal', 'Battalion 609': 'Vicky Ahuja', 'The Accidental Prime Minister (film)': 'Anupam Kher', 'Why Cheat India': 'Emraan Hashmi', 'Evening Shadows': '

In [74]:
#iii. membership operator
## checking film by its name
print('Mission Mangal' in movies)
print("Hera Pheri" in movies)

##checking by its value
print("Akshay Kumar" in movies.values)
print("Deep Shrestha" in movies.values)

True
False
True
False


In [80]:
##iv. looping 
for i in movies:
    print(i)## values will be printed
#to print index
for i in movies.index:
    print(i)

Uri: The Surgical Strike
Battalion 609
The Accidental Prime Minister (film)
Why Cheat India
Evening Shadows
Soni (film)
Fraud Saiyaan
Bombairiya
Manikarnika: The Queen of Jhansi
Thackeray (film)
Amavas
Gully Boy
Hum Chaar
Total Dhamaal
Sonchiriya
Badla (2019 film)
Mard Ko Dard Nahi Hota
Hamid (film)
Photograph (film)
Risknamaa
Mere Pyare Prime Minister
22 Yards
Kesari (film)
Notebook (2019 film)
Junglee (2019 film)
Gone Kesh
Albert Pinto Ko Gussa Kyun Aata Hai?
The Tashkent Files
Kalank
Setters (film)
Student of the Year 2
PM Narendra Modi
De De Pyaar De
India's Most Wanted (film)
Yeh Hai India
Khamoshi (2019 film)
Kabir Singh
Article 15 (film)
One Day: Justice Delivered
Hume Tumse Pyaar Kitna
Super 30 (film)
Family of Thakurganj
Batla House
Jhootha Kahin Ka
Judgementall Hai Kya
Chicken Curry Law
Arjun Patiala
Jabariya Jodi
Pranaam
The Sky Is Pink
Mission Mangal
Saaho
Dream Girl (2019 film)
Section 375
The Zoya Factor (film)
Pal Pal Dil Ke Paas
Prassthanam
P Se Pyaar F Se Faraar
Ghost 

In [82]:
#v.. arithmetic operators
vk.values+100 #this is possible because of broadcasting 


array([101, 123, 113, 112, 101, 109, 134, 100, 121, 103, 110, 138, 103,
       111, 150, 102, 122, 119, 116, 115, 120, 138, 119, 124, 107, 102,
       116, 117, 124, 138, 134, 142, 113, 158, 103, 114, 137, 109, 123,
       112, 171, 135, 130, 156, 167, 127, 127, 139, 115, 111, 131, 170,
       108, 135, 108, 106, 157, 122, 116, 104, 116, 118, 145, 109, 136,
       109, 103, 173, 142, 124, 151, 135, 158, 165, 101, 111, 101, 132,
       125, 157, 193, 199, 117, 114, 156, 149, 100, 131, 121, 104, 100,
       135, 100, 104, 110, 127, 167, 138, 173, 113, 141, 118, 151, 162,
       135, 101, 134, 148, 132, 182, 119, 144, 101, 112, 112, 175, 179,
       133, 180, 200, 114, 152, 208, 120, 107, 209, 175, 213, 154, 100,
       154, 162, 128, 164, 100, 110, 155, 120, 106, 105, 158, 131, 121,
       157, 192, 130, 118, 168, 132, 108, 139, 170, 148, 112, 104, 106,
       146, 103, 123, 184, 141, 167, 108, 200, 109, 113, 123, 125, 116,
       118, 109, 107, 129, 101, 172, 143, 143, 190, 148, 114, 13

In [85]:
#relational operators
vk.values>50 #gives boolean array based on the condition

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False,  True,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False, False,  True,  True, False, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
       False,  True,  True, False,  True,  True, False, False,  True,
        True,  True,